name: Instagram Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Instagram bot script
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      run: |
        python instagram_post_bot.py
      continue-on-error: true  # Ensure the workflow continues even if this step fails

    - name: Upload screenshot artifacts
      if: always()  # Ensure this step runs regardless of previous steps' outcomes
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: |
          post_page.png
          image_uploaded.png
        retention-days: 7  # Optional: How many days to keep the artifact
