    - name: List directory contents
      run: ls -al

    - name: Upload screenshot artifacts
      if: always()  # Ensure this step runs regardless of previous steps' outcomes
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: |
          ./post_page.png
          ./image_uploaded.png
        retention-days: 7  # Optional: How many days to keep the artifact
